basePath: /api/v1
definitions:
  request.CreateJobRequest:
    properties:
      budget:
        type: number
      description:
        type: string
      status:
        enum:
        - open
        - in_progress
        - completed
        - closed
        type: string
      title:
        type: string
      umkm_id:
        type: integer
    required:
    - budget
    - description
    - title
    - umkm_id
    type: object
  request.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  request.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      role:
        enum:
        - admin
        - umkm
        - freelancer
        type: string
    required:
    - email
    - password
    - role
    type: object
  response.JobResponse:
    properties:
      budget:
        type: number
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      status:
        type: string
      title:
        type: string
      umkm_id:
        type: integer
      updated_at:
        type: string
    type: object
  response.UserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      is_active:
        type: boolean
      role:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the official API documentation for the Jobshare platform (Auth,
    UMKM Profiles, and Job Vacancies).
  termsOfService: http://swagger.io/terms/
  title: Jobshare Backend API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: Authenticate user based on email and password.
      parameters:
      - description: Login Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.UserResponse'
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user into the system with a specific role (admin,
        umkm, freelancer).
      parameters:
      - description: Register Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.UserResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Register a new account (UMKM / Freelancer)
      tags:
      - Auth
  /jobs:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all available job vacancies.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/response.JobResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all job vacancies
      tags:
      - Jobs
    post:
      consumes:
      - application/json
      description: Post a new job vacancy into the system by an UMKM.
      parameters:
      - description: Create Job Payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.CreateJobRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.JobResponse'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: Create a new job vacancy (UMKM)
      tags:
      - Jobs
  /jobs/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve details of a specific job vacancy using its unique ID.
      parameters:
      - description: Job ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.JobResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties: true
            type: object
      summary: Get job vacancy by ID
      tags:
      - Jobs
swagger: "2.0"
